name: Build macOS
on: 
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 2025'te LTS sürümü
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --prefer-offline
        
      - name: Build application
        run: npm run dist
        env:
          CI: true
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mac-DMG
          path: dist/*.dmg
          retention-days: 7
          
      - name: Notify Slack (opsiyonel)
        if: failure()
        uses: slackapi/slack-github-action@v2
        with:
          channel-id: 'build-notifications'
          slack-message: 'Build failed: ${{ github.workflow }}'
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
