name: Build Unsigned Mac
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build unsigned
        run: |
          npm run build
          npx electron-builder --mac dir \
            --config.mac.identity=null \
            --config.mac.gatekeeperAssess=false
